package it.epicode.entities;

public enum Generi {
    BIOGRAFIA, STORICO, GIALLO, THRILLER, AVVENTURA,
    FANTASCIENZA, FANTASY, HORROR, YOUNG_ADULT,
    FORMAZIONE, ROMANCE, COMMEDIA, TRAGEDIA, SAGGIO


}
